### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by hai3009** [sam0402/ArchQ#1]
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/install.sh | bash安装不了，有没有详细的教程

**Comment by sam0402** [comment]
http://www.stsd99.com/phpBB3/viewtopic.php?f=61&t=3210&sid=188b3a187bbf20b5f27bef2c1a013f37

**Comment by hai3009** [comment]
多谢你的回复，我USB启动后输入命令curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/install.sh | bash就不动了。

**Comment by sam0402** [comment]
先執行 `curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/install`
確認有沒有跑出安裝程式的內容，如果有，才再加入` | bash`來執行安裝程式。
可以用上下鍵來回溯之前下過的指令。
注意：英文大小寫有分。

**Comment by godjack0709** [comment]
![PXL_20220822_133850609](https://user-images.githubusercontent.com/39131472/185938068-b5a8e819-9236-4464-a7d8-dc6c73a8044f.jpg)
Sam大您好，我是遇到如圖片的問題
應該是有個grub的套件更新了所以網站抓不到變error

**Comment by godjack0709** [comment]
> 先執行 `curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/install.sh` 確認有沒有跑出安裝程式的內容，如果有，才再加入` | bash`來執行安裝程式。 可以用上下鍵來回溯之前下過的指令。 注意：英文大小寫有分。

![185938068-b5a8e819-9236-4464-a7d8-dc6c73a8044f](https://user-images.githubusercontent.com/39131472/185963977-b539eb5f-c4e6-4df6-8ab7-f9cb4177403e.jpg)
Sam大您好，我是遇到如圖片的問題
應該是有個grub的套件更新了所以網站抓不到變error

**Comment by sam0402** [comment]
這應該是Arch Linux 提供下載的Server 還沒更新完成，這不算小弟install 程式的問題，小弟無能為力，只等一段時間再試看看。

**Comment by hai3009** [comment]
sam，你好！停留在此界面上不网，怎么解决？
![微信图片_20220917193256](https://user-images.githubusercontent.com/60032719/190854563-361aa4af-a2e8-49e0-bc5e-af4adf885480.jpg)

**Comment by hai3009** [comment]
上不了网

**Comment by sam0402** [comment]
http://www.stsd99.com/phpBB3/viewtopic.php?f=61&t=3210&sid=c82234cf9716f21b8202ee5d519cee6f#p20931
此頁最後一段有說明。

**Comment by hai3009** [comment]
![捕获](https://user-images.githubusercontent.com/60032719/190880967-16501e53-92ee-4cfe-8065-102ca7760537.PNG)
这段吗？我目前主要连上网，查不到ip

**Comment by sam0402** [comment]
試試：ssh '帳號名稱'@'安裝時輸入的電腦名稱'.local

**Comment by hai3009** [comment]
连接不上网卡，还是不能SSH

**Comment by sam0402** [comment]
支援的網卡：Intel e100, e1000, 82575/82576(IGB) , I225-LM/I225-V (IGC), Realtek RTL8129/8130/8139/8111/8168/8411
USB網卡：Realtek RTL8152/8153、ASIX AX88179/178A
若不是這裡面的，無法使用

**Comment by lin-silas** [comment]
我也遇過這個問題，買個便宜的 USB 網卡接上去就行了。

**Comment by quattr0** [comment]
Greetings,

Could you advise if anything I could do to pass this error? Trying to install it on Intel NUC i5.  Thank you.

![20221204_185745](https://user-images.githubusercontent.com/26072978/205718403-53e539c4-e5bb-4ab7-b387-c10b3354010f.jpg)

**Comment by sam0402** [comment]
Please use UEFI Boot Mode，not Legacy BIOS Boot Mode.

**Comment by quattr0** [comment]
OK, thanks. Now how do I pass "No Sound Device" when configuring SqueezeLight? I have a USB DAC.  Initially during installation, I selected default: CARD...instead of iec958  How do I change it iec958 if that's the correct value?

Thanks again.
![nosound](https://user-images.githubusercontent.com/26072978/206088745-6ebecee1-3382-4b65-b79c-05357f90d7f6.JPG)

**Comment by quattr0** [comment]
Disregard....DAC wasn't on. 

Which hardware you think will clearly see the difference in SQ? My i5 doesn't, so far, sound any better than Pi4 yet. Any recommendations on hardware or settings would be appreciated.

Thank you for this.
