### ISSUE TITLE
Adding radiostreams via myMPD causes error "Unsupported URI scheme"

### ISSUE THREAD

**Issue by d3m0naz** [sam0402/ArchQ#6]
Hi sam0402,
when i try to add a radio stream via the myMPD webinterface MPD gives me the follwing error:
"Unsupported URI scheme".

Is there a fix available?
(maybe mpd compiled with libcurl support?)

Thank you!

**Comment by sam0402** [comment]
Install the MPD stream version as below:
wget -P /tmp https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/mpd-stream-0.23.14-12-x86_64.pkg.tar.zst
sudo pacman -U --noconfirm /tmp/mpd-stream-0.23.14-12-x86_64.pkg.tar.zst

**Comment by d3m0naz** [comment]
Ok, this works . No more URI scheme errors. Thank you.
